version: '3.4'

services:
  app-server:
    build: .
    environment:
      - ENV_MODE=production
    volumes:
      - ./data:/data
    command: gunicorn -b "0.0.0.0:3000" -w 4 app:app
    ports:
      - 9080:3000
  